### PR TITLE
Use strict_types and final keyword

### PR DESCRIPTION
**Pull request by JesusValera**
Add two new recommendations.

### CODE REVIEW

**Comment by JesusValera** [comment]
Strict types: https://stackoverflow.com/questions/48723637/what-does-strict-types-do-in-php
About final classes:
https://matthiasnoback.nl/2018/09/final-classes-by-default-why/
https://ocramius.github.io/blog/when-to-declare-classes-final/
Ocramius is not someone (https://twitter.com/Ocramius) :new_moon_with_face:

**Comment by Eighke** [comment]
> As I can't really agree with strict types declaration (because this can be set globally), I must admit I was considering the second option.

No it cannot be set globally, else all the used libraries will be set to strict, and they may fail (it should not, but you don't know :)).

Now the problem using strict is that the current code may need to be adapted. For example if you are using Laravel `$request->get()` it will probably return a `string`, and most of the time we are using it as it. So it will need to cast it to the good type first.

> I mean, the responsibility of decide how to convert or cast one strict type must be from programmer and not from programming language...
> For this reason, if you define strict types in a function who has a int parameter, it must always be a int type and not from a string or float... and use exceptions when this case happen...

Using strict by default everywhere is the same as  "from programming language". :)

--------------------

Regarding the `final` I disagree, Composition can just be "preferred" behaviour, no need to require `final`. It can be very frustrating to recreate the whole class when you to override a simple method (and no hook are available). 

Maybe for the classes of a `project`. But definitely not for the libraries one.

**Comment by JesusValera** [comment]
> Regarding the `final` I disagree, Composition can just be "preferred" behaviour, no need to require `final`. It can be very frustrating to recreate the whole class when you to override a simple method (and no hook are available).
> 
> Maybe for the classes of a `project`. But definitely not for the libraries one.

I completely agree with you.
Final class for sure are not for libraries, they are mostly for project classes.
Although, the point is you have other ways 'to extend' a class, for example, using composition as you said or even using decorator pattern for example.
We always inherit from interfaces and abstract classes but maybe, in some situations, we want to inherit from a simple class, in that situations, maybe drop the final class is the best option, so, that's not a bad thing but maybe you are creating a fragile code.
But if you have to modify a class and it is already final, you are able to modify it and you can be sure there are no child classes who may modify their behaviour because of their parent.

**Comment by Haru0** [comment]
Another disadvantage of introducing the `final` keyword to our codebase will result in failing unit tests as final classes cannot be mocked.

> There are, however, walkarounds. Please refer to [dg/bypass-finals](https://github.com/dg/bypass-finals), for example.

**Pull request closed without merging**
